FROM public.ecr.aws/lambda/python:3.9

#Copys files over
COPY ../Item_Delete.py ${LAMBDA_TASK_ROOT}
COPY ../requirements.txt .

#Installs dependencies
RUN pip3 install -r requirements.txt --target "${LAMBDA_TASK_ROOT}"

#This makes it the entry point
CMD ["Item_Delete.lambda_handler"]